---
title: "Random forest"
output: html_notebook
---

```{r include=FALSE}
set.seed(420)
library(dplyr)
library(randomForest)
library(pROC)
```

Random forest model 

# loading data
```{r eval=FALSE, include=FALSE}
setwd("C:/Users/D/Desktop/Stats/sem4/Big data and platforms/Churn")
telco <- read.csv("telco_train.csv")
```

# same data prep
loaded in previous page

```{r include=FALSE}
# train has to be changed by the imputed data.
attach(telco)
Payment_Delay_level <- mutate(telco, Payment_Delay_level = ifelse(COUNT_PAYMENT_DELAYS_1YEAR <= 4,1,
                                   ifelse(COUNT_PAYMENT_DELAYS_1YEAR %in% 5:8, 2,
                                   ifelse(COUNT_PAYMENT_DELAYS_1YEAR >= 8, 3, 0 ))))

      
hist(Payment_Delay_level$Payment_Delay_level)
telco$Payment_Delay_level <- Payment_Delay_level$Payment_Delay_level

hist(CLV)
summary(CLV)

CLV_level <- mutate(telco, CLV_level = ifelse(CLV < 11398 , 1,
                          ifelse(CLV %in% 11398:16891, 2,
                          ifelse(CLV >= 16892, 3 ,0 ))))

hist(CLV_level$CLV_level)

telco$CLV_Level <- CLV_level$CLV_level

telco$delta_m3_m6 <- COMPLAINT_3MONTHS-COMPLAINT_6MONTHS
telco$delta_m1_m3 <- COMPLAINT_1MONTH-COMPLAINT_3MONTHS

dt1 <- as.Date("2013-12-1")
telco$Time_Customer <- difftime(dt1, START_DATE, units = "weeks")

attach(telco)
telco$Time_Customer <- as.numeric(Time_Customer)
```

## removing some features 
```{r}
telco$ID <- NULL # ID has no value 
telco$FIN_STATE <- NULL # too many missings
telco$START_DATE <- NULL # we took weeks client instead
```

# dealing with missing values 

```{r}
telcoimputed <- rfImpute(CHURN ~ ., telco, iter = 4, ntree = 100)
```


# splitting the data 
```{r}
# making the variables numeric
train.num <- as.data.frame(lapply(telcoimputed, as.numeric))
# we need churn to be a character 
train.num$CHURN <- as.factor(train.num$CHURN)

attach(train.num)

# get the numb 70/30 training test split
numberOfTrainingSamples <- round(length(CHURN) * .7)

# training data
train_data <- train.num[1:numberOfTrainingSamples,]
test_data <- train.num[-(1:numberOfTrainingSamples),]
```





# Build that forest 
## easy model

```{r}

rf.1 <- randomForest(CHURN ~ . , data = train_data, 
                     importance = T,
                     confusion = T,
                     ntree = 1000,
                     type = classification)

plot(rf.1)

rf.1


```

# Results

how to upload these?
ID,CHURN
17030,0.42
14981,0.21

```{r}
#confusion matrix
C.Pred <- predict(rf.1, newdata=test_data)

cm.1 <- table(C.Pred, test_data$CHURN)

results <- cbind(C.Pred, test_data$CHURN)

# Accuracy 
(sum(diag(cm.1)))/sum(cm.1)
accuracy <- (sum(diag(cm.1)))/sum(cm.1)
# ROC 
rf.roc<-roc(train_data$CHURN,rf.1$votes[,1])
plot(rf.roc)
auc(rf.roc)

```

Not too bad this AUC of 92% 

